export const productDetailsData = [
  {
    id: 1,
    name: "چای سرگل ، ویژه میهمانی ها ، اعلا و دلچسب",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "black",
    subCategoryTag: "سیاه",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/sargol/sargol-1.jpg",
        thumb: "/images/teas/details/sargol/sargol-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/sargol/sargol-2.jpg",
        thumb: "/images/teas/details/sargol/sargol-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/sargol/sargol-3.jpg",
        thumb: "/images/teas/details/sargol/sargol-3.jpg",
      },
    ],
    price: 320000,
    weight: 1,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 2,
    name: "چای ممتاز ، مصارف روزانه ، خوشرنگ و ناب",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "black",
    subCategoryTag: "سیاه",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/momtaz/momtaz-1.jpg",
        thumb: "/images/teas/details/momtaz/momtaz-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/momtaz/momtaz-2.jpg",
        thumb: "/images/teas/details/momtaz/momtaz-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/momtaz/momtaz-3.jpg",
        thumb: "/images/teas/details/momtaz/momtaz-3.jpg",
      },
    ],
    price: 270000,
    weight: 1,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 180,
    discountPercent: 0,
  },
  {
    id: 3,
    name: "چای شکسته ، ملایم ، مطبوع و اقتصادی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "black",
    subCategoryTag: "سیاه",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/shekaste/shekaste-1.jpg",
        thumb: "/images/teas/details/shekaste/shekaste-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/shekaste/shekaste-2.jpg",
        thumb: "/images/teas/details/shekaste/shekaste-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/shekaste/shekaste-3.jpg",
        thumb: "/images/teas/details/shekaste/shekaste-3.jpg",
      },
    ],
    price: 215000,
    weight: 1,
    rating: 4,
    isFeatured: false,
    inStock: true,
    stockCount: 120,
    discountPercent: 0,
  },
  {
    id: 4,
    name: "چای قلم سوزنی ، رنگ شفاف ، گس مطلوب",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "black",
    subCategoryTag: "سیاه",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/ghalam-soozani/ghalam-soozani-1.jpg",
        thumb: "/images/teas/details/ghalam-soozani/ghalam-soozani-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/ghalam-soozani/ghalam-soozani-2.jpg",
        thumb: "/images/teas/details/ghalam-soozani/ghalam-soozani-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/ghalam-soozani/ghalam-soozani-3.jpg",
        thumb: "/images/teas/details/ghalam-soozani/ghalam-soozani-3.jpg",
      },
    ],
    price: 250000,
    weight: 1,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 170,
    discountPercent: 0,
  },
  {
    id: 5,
    name: "چای قلم درشت ، طرفداران خاص ، دیردم",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "black",
    subCategoryTag: "سیاه",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-1.jpg",
        thumb: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-2.jpg",
        thumb: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-3.jpg",
        thumb: "/images/teas/details/ghalam-dorosht/ghalam-dorosht-3.jpg",
      },
    ],
    price: 190000,
    weight: 1,
    rating: 3,
    isFeatured: false,
    inStock: true,
    stockCount: 170,
    discountPercent: 0,
  },
  {
    id: 6,
    name: "چای سبز ممتاز ، بی نظیر برای تناسب اندام",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "green",
    subCategoryTag: "سبز",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/green-momtaz/green-mom-1.jpg",
        thumb: "/images/teas/details/green-momtaz/green-mom-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/green-momtaz/green-mom-2.jpg",
        thumb: "/images/teas/details/green-momtaz/green-mom-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/green-momtaz/green-mom-3.jpg",
        thumb: "/images/teas/details/green-momtaz/green-mom-3.jpg",
      },
    ],
    price: 310000,
    weight: 1,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 110,
    discountPercent: 0,
  },
  {
    id: 7,
    name: "چای سبز قلم ، طعم ملایم تر به نسبت ممتاز",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "tea",
    categoryTag: "چای",
    subCategory: "green",
    subCategoryTag: "سبز",
    gallery: [
      {
        id: 1,
        img: "/images/teas/details/green-ghalam/green-ghlm-1.jpg",
        thumb: "/images/teas/details/green-ghalam/green-ghlm-1.jpg",
      },
      {
        id: 2,
        img: "/images/teas/details/green-ghalam/green-ghlm-2.jpg",
        thumb: "/images/teas/details/green-ghalam/green-ghlm-2.jpg",
      },
      {
        id: 3,
        img: "/images/teas/details/green-ghalam/green-ghlm-3.jpg",
        thumb: "/images/teas/details/green-ghalam/green-ghlm-3.jpg",
      },
    ],
    price: 220000,
    weight: 1,
    rating: 4,
    isFeatured: false,
    inStock: true,
    stockCount: 120,
    discountPercent: 0,
  },
  {
    id: 8,
    name: "برنج هاشمی معطر 5 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-5k-big-1.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-5k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-5k-big-2.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-5k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-5k-big-3.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-5k-small-3.jpg",
      },
    ],
    price: 600000,
    weight: 5,
    rating: 5,
    isFeatured: false,
    inStock: true,
    stockCount: 250,
    discountPercent: 0,
  },
  {
    id: 9,
    name: "برنج هاشمی معطر 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-10k-big-1.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-5k-big-2.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-5k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-atri/hashemi-atri-5k-big-3.jpg",
        thumb: "/images/rice/details/hashemi-atri/hashemi-atri-5k-small-3.jpg",
      },
    ],
    price: 1200000,
    weight: 10,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 250,
    discountPercent: 0,
  },
  {
    id: 10,
    name: "برنج هاشمی دودی 5 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-big-1.jpg",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-big-2.png",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-small-2.png",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-big-3.png",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-5k-small-3.png",
      },
    ],
    price: 675000,
    weight: 5,
    rating: 4,
    isFeatured: false,
    inStock: true,
    stockCount: 250,
    discountPercent: 0,
  },
  {
    id: 11,
    name: "برنج هاشمی دودی 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-big-1.jpg",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-big-2.jpg",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-big-3.jpg",
        thumb:
          "/images/rice/details/hashemi-doodi/hashemi-doodi-10k-small-3.jpg",
      },
    ],
    price: 1350000,
    weight: 10,
    rating: 4,
    isFeatured: true,
    inStock: true,
    stockCount: 250,
    discountPercent: 0,
  },
  {
    id: 12,
    name: "نیم دانه هاشمی عطری 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-nim/hashemi-nim-10k-big-1.jpg",
        thumb: "/images/rice/details/hashemi-nim/hashemi-nim-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-nim/hashemi-nim-10k-big-2.jpg",
        thumb: "/images/rice/details/hashemi-nim/hashemi-nim-10k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-nim/hashemi-nim-10k-big-3.jpg",
        thumb: "/images/rice/details/hashemi-nim/hashemi-nim-10k-small-3.jpg",
      },
    ],
    price: 650000,
    weight: 10,
    rating: 3,
    isFeatured: false,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 13,
    name: "برنج شکسته هاشمی عطری 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "hashemi",
    subCategoryTag: "هاشمی",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-big-1.jpg",
        thumb:
          "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-big-2.jpg",
        thumb:
          "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-big-3.jpg",
        thumb:
          "/images/rice/details/hashemi-shekaste/hashemi-shek-10k-small-3.jpg",
      },
    ],
    price: 850000,
    weight: 10,
    rating: 4,
    isFeatured: false,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 14,
    name: "برنج صدری معطر 5 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "sadri",
    subCategoryTag: "صدری",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/sadri-atri/sadri-atri-5k-big-1.jpg",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-5k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/sadri-atri/sadri-atri-5k-big-2.jpg",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-5k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/sadri-atri/sadri-atri-5k-big-3.jpg",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-5k-small-3.jpg",
      },
    ],
    price: 750000,
    weight: 5,
    rating: 5,
    isFeatured: false,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 15,
    name: "برنج صدری عطری 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "sadri",
    subCategoryTag: "صدری",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/sadri-atri/sadri-atri-10k-big-1.jpg",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/sadri-atri/sadri-atri-10k-big-2.jpg",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-10k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/sadri-atri/sadri-atri-10k-big-3.png",
        thumb: "/images/rice/details/sadri-atri/sadri-atri-10k-small-3.png",
      },
    ],
    price: 1500000,
    weight: 10,
    rating: 5,
    isFeatured: true,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 16,
    name: "برنج صدری دودی 5 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "sadri",
    subCategoryTag: "صدری",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-5k-big-1.jpg",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-5k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-5k-big-2.jpg",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-5k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-5k-big-3.png",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-5k-small-3.png",
      },
    ],
    price: 850000,
    weight: 5,
    rating: 4,
    isFeatured: true,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
  {
    id: 17,
    name: "برنج صدری دودی 10 کیلویی",
    desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
    category: "rice",
    categoryTag: "برنج",
    subCategory: "sadri",
    subCategoryTag: "صدری",
    gallery: [
      {
        id: 1,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-10k-big-1.jpg",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-10k-small-1.jpg",
      },
      {
        id: 2,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-5k-big-2.jpg",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-5k-small-2.jpg",
      },
      {
        id: 3,
        img: "/images/rice/details/sadri-doodi/sadri-doodi-5k-big-3.png",
        thumb: "/images/rice/details/sadri-doodi/sadri-doodi-5k-small-3.png",
      },
    ],
    price: 1700000,
    weight: 10,
    rating: 4,
    isFeatured: true,
    inStock: true,
    stockCount: 150,
    discountPercent: 0,
  },
];
