export const productsData=[
    {
        id:1,
        name:"چای سرگل ، ویژه میهمانی ها ، اعلا و دلچسب",
        category:"tea",
        subCategory:"black",
        img:"/images/teas/sargol.jpg",
        price:320000,
        weight:1,
        rating: 5,
        sellCount:68,
        isFeatured:true,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:2,
        name:"چای ممتاز ، مصارف روزانه ، خوشرنگ و ناب",
        category:"tea",
        subCategory:"black",
        img:"/images/teas/momtaz.jpg",
        price:270000,
        weight:1,
        rating: 5,
        sellCount:74,
        isFeatured:true,
        inStock:true,
        stockCount:180,
        discountPercent:0
    },
    {
        id:3,
        name:"چای شکسته ، ملایم ، مطبوع و اقتصادی",
        category:"tea",
        subCategory:"black",
        img:"/images/teas/shekaste.jpg",
        price:215000,
        weight:1,
        rating: 4,
        sellCount:48,
        isFeatured:false,
        inStock:true,
        stockCount:120,
        discountPercent:0
    },
    {
        id:4,
        name:"چای قلم سوزنی ، رنگ شفاف ، گس مطلوب",
        category:"tea",
        subCategory:"black",
        img:"/images/teas/ghalam-soozani.jpg",
        price:250000,
        weight:1,
        rating: 5,
        sellCount:71,
        isFeatured:true,
        inStock:true,
        stockCount:170,
        discountPercent:0
    },
    {
        id:5,
        name:"چای قلم درشت ، طرفداران خاص ، دیردم",
        category:"tea",
        subCategory:"black",
        img:"/images/teas/ghalam-dorosht.jpg",
        price:190000,
        weight:1,
        rating: 3,
        sellCount:35,
        isFeatured:false,
        inStock:true,
        stockCount:170,
        discountPercent:0
    },
     {
        id:6,
        name:"چای سبز ممتاز ، بی نظیر برای تناسب اندام",
        category:"tea",
        subCategory:"green",
        img:"/images/teas/green-momtaz.jpg",
        price:310000,
        weight:1,
        rating: 5,
        sellCount:66,
        isFeatured:true,
        inStock:true,
        stockCount:110,
        discountPercent:0
    },
     {
        id:7,
        name:"چای سبز قلم ، طعم ملایم تر به نسبت ممتاز",
        category:"tea",
        subCategory:"green",
        img:"/images/teas/green-ghlm.jpg",
        price:220000,
        weight:1,
        rating: 4,
        sellCount:53,
        isFeatured:false,
        inStock:true,
        stockCount:120,
        discountPercent:0
    },
    {
        id:8,
        name:"برنج هاشمی معطر 5 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-atri-5kilo.jpg",
        price:600000,
        weight:5,
        rating: 5,
        sellCount:62,
        isFeatured:false,
        inStock:true,
        stockCount:250,
        discountPercent:0
    },
    {
        id:9,
        name:"برنج هاشمی معطر 10 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-atri-10kilo.jpg",
        price:1200000,
        weight:10,
        rating: 5,
        sellCount:75,
        isFeatured:true,
        inStock:true,
        stockCount:250,
        discountPercent:0
    },
    {
        id:10,
        name:"برنج هاشمی دودی 5 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-doodi-5kilo.jpg",
        price:675000,
        weight:5,
        rating: 4,
        sellCount:58,
        isFeatured:false,
        inStock:true,
        stockCount:250,
        discountPercent:0
    },
    {
        id:11,
        name:"برنج هاشمی دودی 10 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-doodi-10kilo.jpg",
        price:1350000,
        weight:10,
        rating: 4,
        sellCount:67,
        isFeatured:true,
        inStock:true,
        stockCount:250,
        discountPercent:0
    },
    {
        id:12,
        name:"نیم دانه هاشمی عطری 10 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-nim-10kilo.jpg",
        price:650000,
        weight:10,
        rating: 3,
        sellCount:40,
        isFeatured:false,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:13,
        name:"برنج شکسته هاشمی عطری 10 کیلویی",
        category:"rice",
        subCategory:"hashemi",
        img:"/images/rice/hashemi-shekaste-10kilo.jpg",
        price:850000,
        weight:10,
        rating: 4,
        sellCount:50,
        isFeatured:false,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:14,
        name:"برنج صدری معطر 5 کیلویی",
        category:"rice",
        subCategory:"sadri",
        img:"/images/rice/sadri-atri-5kilo.jpg",
        price:750000,
        weight:5,
        rating: 5,
        sellCount:72,
        isFeatured:false,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:15,
        name:"برنج صدری عطری 10 کیلویی",
        category:"rice",
        subCategory:"sadri",
        img:"/images/rice/sadri-atri-10kilo.jpg",
        price:1500000,
        weight:10,
        rating: 5,
        sellCount:78,
        isFeatured:true,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:16,
        name:"برنج صدری دودی 5 کیلویی",
        category:"rice",
        subCategory:"sadri",
        img:"/images/rice/sadri-doodi-5kilo.jpg",
        price:850000,
        weight:5,
        rating: 4,
        sellCount:73,
        isFeatured:true,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },
    {
        id:17,
        name:"برنج صدری دودی 10 کیلویی",
        category:"rice",
        subCategory:"sadri",
        img:"/images/rice/sadri-doodi-10kilo.jpg",
        price:1700000,
        weight:10,
        rating: 4,
        sellCount:70,
        isFeatured:true,
        inStock:true,
        stockCount:150,
        discountPercent:0
    },



]